name: Auto Merge PRs

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  pull_request:
    types:
      - labeled
      - synchronize
      - opened

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: auto-merge
        name: auto-merge
        uses: "pascalgn/automerge-action@v0.16.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          required-labels: auto-merge
          merge-method: rebase
          dry-run: true
