name: Auto Merge PRs

on:
  workflow_dispatch:
    inputs:
      pull-request:
        description: Pull Request Number
        required: false
  schedule:
    - cron: 0 * * * *
  pull_request_review:
    types:
      - submitted
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
      - edited
      - labeled
      - unlabeled
      - ready_for_review

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - id: auto-merge
        name: auto-merge
        uses: "pascalgn/automerge-action@v0.16.2"
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request: ${{ github.event.inputs.pull-request }}
          required-labels: auto-merge
          merge-method: rebase
