name: Scrape Mortage Rates, Commit and Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun Installation
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install

      - name: Run the scraper script for mortgage rates
        run: bun run bin/scrape-mortgage-rates.ts

      - name: Sleep for 2 seconds
        run: sleep 2s
        shell: bash

      - name: Run the scraper script for personal loan rates
        run: bun run bin/scrape-personal-loan-rates.ts

      - name: Sleep for 2 seconds
        run: sleep 2s
        shell: bash

      - name: Run the scraper script for car loan rates
        run: bun run bin/scrape-car-loan-rates.ts

      - name: Sleep for 2 seconds
        run: sleep 2s
        shell: bash

      - name: Run the scraper script for credit card rates
        run: bun run bin/scrape-credit-card-rates.ts

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/mortgage-rates.json
          git add data/personal-loan-rates.json
          git add data/car-loan-rates.json
          git add data/credit-card-rates.json
          git commit -m "Update scraped tables" -a || exit 0
          git push

      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify src/index.ts
