name: Schedule Scrape and Commit to PR

on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  schedule-scrape-and-commit-pr:
    runs-on: ubuntu-latest

    env:
      changes: false # Set the default value for `changes`

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun Installation
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install

      - name: Run the scraper script for mortgage rates
        run: bun run bin/scrape-mortgage-rates.ts

      - name: Run the scraper script for personal loan rates
        run: bun run bin/scrape-personal-loan-rates.ts

      - name: Run the scraper script for car loan rates
        run: bun run bin/scrape-car-loan-rates.ts

      - name: Run the scraper script for credit card rates
        run: bun run bin/scrape-credit-card-rates.ts

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes=true" >> $GITHUB_ENV

      - name: Setup GitHub CLI
        if: env.changes == 'true'
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Configure Git
        if: env.changes == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Create or Update Branch and PR
        if: env.changes == 'true'
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          BRANCH_NAME="update-rates-$(date +%Y-%m-%d-%H-%M-%S)"

          git fetch origin

          echo "Creating new branch: $BRANCH_NAME"
          git checkout -b $BRANCH_NAME

          git add data/*.json
          git commit -m "Update scraped tables" || echo "No changes to commit"

          # Push changes
          git push -u origin $BRANCH_NAME

          # Check for existing PR and create/update accordingly
          PR_NUMBER=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            # Create a new PR and add a label
            gh pr create --base main --head $BRANCH_NAME --title "Update Rates" --body "Automated rates update." --label "auto-merge"
          else
            echo "PR already exists with number: $PR_NUMBER"
            # Optionally, update the existing PR, e.g., add a label
            gh pr edit "$PR_NUMBER" --add-label "auto-merge"
          fi
