name: Scrape Mortage Rates, Commit and Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs at the start of every hour
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Verify Bun Installation
        run: bun --version

      - name: Install dependencies with Bun
        run: bun install

      - name: Run the scraper script with Bun
        run: bun run bin/scrape-mortgage-rates.ts

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add data/mortgage-rates.json
          git commit -m "Update scraped table" -a || exit 0
          git push

      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: deploy --minify src/index.ts
